[package]
name = "actx"
version = "0.1.0"
authors = ["JulienBe <bertozzijulien@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"